package com.privatecloud.users.model;

// Generated May 2, 2015 5:45:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * Alarm generated by hbm2java
 */
public class Alarm implements java.io.Serializable {

	private Integer alarmid;
	private int vmId;
	private String propertyId;
	private String thresholdValue;
	private String limitExceed;

	public Alarm() {
	}

	public Alarm(int vmId, String propertyId, String thresholdValue,
			String limitExceed) {
		this.vmId = vmId;
		this.propertyId = propertyId;
		this.thresholdValue = thresholdValue;
		this.limitExceed = limitExceed;
	}

	public Integer getAlarmid() {
		return this.alarmid;
	}

	public void setAlarmid(Integer alarmid) {
		this.alarmid = alarmid;
	}

	public int getVmId() {
		return this.vmId;
	}

	public void setVmId(int vmId) {
		this.vmId = vmId;
	}

	public String getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(String propertyId) {
		this.propertyId = propertyId;
	}

	public String getThresholdValue() {
		return this.thresholdValue;
	}

	public void setThresholdValue(String thresholdValue) {
		this.thresholdValue = thresholdValue;
	}

	public String getLimitExceed() {
		return this.limitExceed;
	}

	public void setLimitExceed(String limitExceed) {
		this.limitExceed = limitExceed;
	}

}
