package com.privatecloud.users.model;

// Generated May 3, 2015 12:42:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * Params generated by hbm2java
 */
public class Params implements java.io.Serializable {

	private Integer paramsId;
	private String name;

	public Params() {
	}

	public Params(String name) {
		this.name = name;
	}

	public Integer getParamsId() {
		return this.paramsId;
	}

	public void setParamsId(Integer paramsId) {
		this.paramsId = paramsId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
