package com.privatecloud.users.model;
// Generated Apr 10, 2015 8:33:11 PM by Hibernate Tools 3.4.0.CR1


/**
 * Vm generated by hbm2java
 */
public class Vm implements java.io.Serializable {

	
	/**
	 * 
	 */
	private Integer Id;
	private static final long serialVersionUID = 4739301756478474378L;
	private String vmname;
	private String stat;
	private String os;
	

	public Vm() {
	}

	public Vm ( String vmname, String os) {
		this.vmname = vmname;
		this.os=os;
		
	}
	
	public Integer getid()
	{
		return this.Id;
	}
	
	public void setid(Integer Id)
	{
		this.Id = Id;
	}

	public String getVmname() {
		return this.vmname;
	}

	public void setVmname(String vmname) {
		this.vmname = vmname;
	}

	public String getStat() {
		return this.stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}
	
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	
}
