// default package
// Generated Apr 10, 2015 8:33:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Vm generated by hbm2java
 */
public class Vm implements java.io.Serializable {

	private Int Id;
	private String vmname;
	private String stat;
	private String os;
	

	public Vm() {
	}

	public Vm(Int Id, String vmname, String stat) {
		this.Id = Id;
		this.vmname = vmname;
		this.stat = stat;
		
	}

	public Int getid(){
		return this.Id;
	}
	
	public void setid(Int Id){
		this.Id = Id;
	}
	
	public String getVmname() {
		return this.vmname;
	}

	public void setVmname(String vmname) {
		this.vmname = vmname;
	}

	public String getStat() {
		return this.stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}

	
}
