// default package
// Generated Apr 10, 2015 8:33:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Vm generated by hbm2java
 */
public class Vm implements java.io.Serializable {

	private String vmname;
	private String stat;
	private Date created;
	private Date modified;

	public Vm() {
	}

	public Vm(String vmname, String stat, Date created, Date modified) {
		this.vmname = vmname;
		this.stat = stat;
		this.created = created;
		this.modified = modified;
	}

	public String getVmname() {
		return this.vmname;
	}

	public void setVmname(String vmname) {
		this.vmname = vmname;
	}

	public String getStat() {
		return this.stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

}
